// lodges
export const START_LOADING = 'START_LOADING'

export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS'
export const UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL'

export const DELETE_LODGE_SUCCESS = 'DELETE_LODGE_SUCCESS'
export const DELETE_LODGE_FAIL = 'DELETE_LODGE_FAIL'

export const EDIT_LODGE_SUCCESS = 'EDIT_LODGE_SUCCESS'
export const EDIT_LODGE_FAIL = 'EDIT_LODGE_FAIL'

export const ADD_LODGE_SUCCESS = 'ADD_LODGE_SUCCESS'
export const ADD_LODGE_FAIL = 'ADD_LODGE_FAIL'

// lodgeForm
export const SET_LODGE_DATA = 'SET_LODGE_DATA'
export const RESET_LODGE_DATA = 'RESET_LODGE_DATA'

export const CHANGE_INPUT = 'CHANGE_INPUT'

export const ADD_ADJACENT_LODGE = 'ADD_ADJACENT_LODGE'
export const EDIT_ADJACENT_LODGE = 'EDIT_ADJACENT_LODGE'
export const REMOVE_ADJACENT_LODGE = 'REMOVE_ADJACENT_LODGE'