export const START_LOADING = 'START_LOADING'

export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS'
export const UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL'

export const DELETE_LODGE_SUCCESS = 'DELETE_LODGE_SUCCESS'
export const DELETE_LODGE_FAIL = 'DELETE_LODGE_FAIL'